package com.lyj.pojo;

import java.io.Serializable;
import java.util.Date;

public class BookKey implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mybook.xm
     *
     * @mbggenerated
     */
    private String xm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mybook.fsr
     *
     * @mbggenerated
     */
    private String fsr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mybook.fsrq
     *
     * @mbggenerated
     */
    private Date fsrq;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mybook.sfflag
     *
     * @mbggenerated
     */
    private String sfflag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table mybook
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mybook.xm
     *
     * @return the value of mybook.xm
     *
     * @mbggenerated
     */
    public String getXm() {
        return xm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mybook.xm
     *
     * @param xm the value for mybook.xm
     *
     * @mbggenerated
     */
    public void setXm(String xm) {
        this.xm = xm == null ? null : xm.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mybook.fsr
     *
     * @return the value of mybook.fsr
     *
     * @mbggenerated
     */
    public String getFsr() {
        return fsr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mybook.fsr
     *
     * @param fsr the value for mybook.fsr
     *
     * @mbggenerated
     */
    public void setFsr(String fsr) {
        this.fsr = fsr == null ? null : fsr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mybook.fsrq
     *
     * @return the value of mybook.fsrq
     *
     * @mbggenerated
     */
    public Date getFsrq() {
        return fsrq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mybook.fsrq
     *
     * @param fsrq the value for mybook.fsrq
     *
     * @mbggenerated
     */
    public void setFsrq(Date fsrq) {
        this.fsrq = fsrq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mybook.sfflag
     *
     * @return the value of mybook.sfflag
     *
     * @mbggenerated
     */
    public String getSfflag() {
        return sfflag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mybook.sfflag
     *
     * @param sfflag the value for mybook.sfflag
     *
     * @mbggenerated
     */
    public void setSfflag(String sfflag) {
        this.sfflag = sfflag == null ? null : sfflag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mybook
     *
     * @mbggenerated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        BookKey other = (BookKey) that;
        return (this.getXm() == null ? other.getXm() == null : this.getXm().equals(other.getXm()))
            && (this.getFsr() == null ? other.getFsr() == null : this.getFsr().equals(other.getFsr()))
            && (this.getFsrq() == null ? other.getFsrq() == null : this.getFsrq().equals(other.getFsrq()))
            && (this.getSfflag() == null ? other.getSfflag() == null : this.getSfflag().equals(other.getSfflag()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mybook
     *
     * @mbggenerated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getXm() == null) ? 0 : getXm().hashCode());
        result = prime * result + ((getFsr() == null) ? 0 : getFsr().hashCode());
        result = prime * result + ((getFsrq() == null) ? 0 : getFsrq().hashCode());
        result = prime * result + ((getSfflag() == null) ? 0 : getSfflag().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mybook
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", xm=").append(xm);
        sb.append(", fsr=").append(fsr);
        sb.append(", fsrq=").append(fsrq);
        sb.append(", sfflag=").append(sfflag);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}