package com.lyj.pojo;

import java.io.Serializable;
import java.util.Date;

public class Book extends BookKey implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mybook.lx
     *
     * @mbggenerated
     */
    private String lx;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mybook.subject
     *
     * @mbggenerated
     */
    private String subject;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mybook.content
     *
     * @mbggenerated
     */
    private String content;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mybook.filename
     *
     * @mbggenerated
     */
    private String filename;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mybook.zt
     *
     * @mbggenerated
     */
    private String zt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mybook.shrq
     *
     * @mbggenerated
     */
    private Date shrq;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mybook.action
     *
     * @mbggenerated
     */
    private String action;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mybook.isread
     *
     * @mbggenerated
     */
    private String isread;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mybook.isok
     *
     * @mbggenerated
     */
    private Integer isok;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mybook.isshow
     *
     * @mbggenerated
     */
    private Integer isshow;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mybook.pkid
     *
     * @mbggenerated
     */
    private Long pkid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mybook.filenr
     *
     * @mbggenerated
     */
    private byte[] filenr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table mybook
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mybook.lx
     *
     * @return the value of mybook.lx
     *
     * @mbggenerated
     */
    public String getLx() {
        return lx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mybook.lx
     *
     * @param lx the value for mybook.lx
     *
     * @mbggenerated
     */
    public void setLx(String lx) {
        this.lx = lx == null ? null : lx.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mybook.subject
     *
     * @return the value of mybook.subject
     *
     * @mbggenerated
     */
    public String getSubject() {
        return subject;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mybook.subject
     *
     * @param subject the value for mybook.subject
     *
     * @mbggenerated
     */
    public void setSubject(String subject) {
        this.subject = subject == null ? null : subject.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mybook.content
     *
     * @return the value of mybook.content
     *
     * @mbggenerated
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mybook.content
     *
     * @param content the value for mybook.content
     *
     * @mbggenerated
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mybook.filename
     *
     * @return the value of mybook.filename
     *
     * @mbggenerated
     */
    public String getFilename() {
        return filename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mybook.filename
     *
     * @param filename the value for mybook.filename
     *
     * @mbggenerated
     */
    public void setFilename(String filename) {
        this.filename = filename == null ? null : filename.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mybook.zt
     *
     * @return the value of mybook.zt
     *
     * @mbggenerated
     */
    public String getZt() {
        return zt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mybook.zt
     *
     * @param zt the value for mybook.zt
     *
     * @mbggenerated
     */
    public void setZt(String zt) {
        this.zt = zt == null ? null : zt.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mybook.shrq
     *
     * @return the value of mybook.shrq
     *
     * @mbggenerated
     */
    public Date getShrq() {
        return shrq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mybook.shrq
     *
     * @param shrq the value for mybook.shrq
     *
     * @mbggenerated
     */
    public void setShrq(Date shrq) {
        this.shrq = shrq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mybook.action
     *
     * @return the value of mybook.action
     *
     * @mbggenerated
     */
    public String getAction() {
        return action;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mybook.action
     *
     * @param action the value for mybook.action
     *
     * @mbggenerated
     */
    public void setAction(String action) {
        this.action = action == null ? null : action.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mybook.isread
     *
     * @return the value of mybook.isread
     *
     * @mbggenerated
     */
    public String getIsread() {
        return isread;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mybook.isread
     *
     * @param isread the value for mybook.isread
     *
     * @mbggenerated
     */
    public void setIsread(String isread) {
        this.isread = isread == null ? null : isread.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mybook.isok
     *
     * @return the value of mybook.isok
     *
     * @mbggenerated
     */
    public Integer getIsok() {
        return isok;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mybook.isok
     *
     * @param isok the value for mybook.isok
     *
     * @mbggenerated
     */
    public void setIsok(Integer isok) {
        this.isok = isok;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mybook.isshow
     *
     * @return the value of mybook.isshow
     *
     * @mbggenerated
     */
    public Integer getIsshow() {
        return isshow;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mybook.isshow
     *
     * @param isshow the value for mybook.isshow
     *
     * @mbggenerated
     */
    public void setIsshow(Integer isshow) {
        this.isshow = isshow;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mybook.pkid
     *
     * @return the value of mybook.pkid
     *
     * @mbggenerated
     */
    public Long getPkid() {
        return pkid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mybook.pkid
     *
     * @param pkid the value for mybook.pkid
     *
     * @mbggenerated
     */
    public void setPkid(Long pkid) {
        this.pkid = pkid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mybook.filenr
     *
     * @return the value of mybook.filenr
     *
     * @mbggenerated
     */
    public byte[] getFilenr() {
        return filenr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mybook.filenr
     *
     * @param filenr the value for mybook.filenr
     *
     * @mbggenerated
     */
    public void setFilenr(byte[] filenr) {
        this.filenr = filenr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mybook
     *
     * @mbggenerated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        Book other = (Book) that;
        return (this.getXm() == null ? other.getXm() == null : this.getXm().equals(other.getXm()))
            && (this.getFsr() == null ? other.getFsr() == null : this.getFsr().equals(other.getFsr()))
            && (this.getFsrq() == null ? other.getFsrq() == null : this.getFsrq().equals(other.getFsrq()))
            && (this.getSfflag() == null ? other.getSfflag() == null : this.getSfflag().equals(other.getSfflag()))
            && (this.getLx() == null ? other.getLx() == null : this.getLx().equals(other.getLx()))
            && (this.getSubject() == null ? other.getSubject() == null : this.getSubject().equals(other.getSubject()))
            && (this.getContent() == null ? other.getContent() == null : this.getContent().equals(other.getContent()))
            && (this.getFilename() == null ? other.getFilename() == null : this.getFilename().equals(other.getFilename()))
            && (this.getZt() == null ? other.getZt() == null : this.getZt().equals(other.getZt()))
            && (this.getShrq() == null ? other.getShrq() == null : this.getShrq().equals(other.getShrq()))
            && (this.getAction() == null ? other.getAction() == null : this.getAction().equals(other.getAction()))
            && (this.getIsread() == null ? other.getIsread() == null : this.getIsread().equals(other.getIsread()))
            && (this.getIsok() == null ? other.getIsok() == null : this.getIsok().equals(other.getIsok()))
            && (this.getIsshow() == null ? other.getIsshow() == null : this.getIsshow().equals(other.getIsshow()))
            && (this.getPkid() == null ? other.getPkid() == null : this.getPkid().equals(other.getPkid()))
            && (this.getFilenr() == null ? other.getFilenr() == null : this.getFilenr().equals(other.getFilenr()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mybook
     *
     * @mbggenerated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getXm() == null) ? 0 : getXm().hashCode());
        result = prime * result + ((getFsr() == null) ? 0 : getFsr().hashCode());
        result = prime * result + ((getFsrq() == null) ? 0 : getFsrq().hashCode());
        result = prime * result + ((getSfflag() == null) ? 0 : getSfflag().hashCode());
        result = prime * result + ((getLx() == null) ? 0 : getLx().hashCode());
        result = prime * result + ((getSubject() == null) ? 0 : getSubject().hashCode());
        result = prime * result + ((getContent() == null) ? 0 : getContent().hashCode());
        result = prime * result + ((getFilename() == null) ? 0 : getFilename().hashCode());
        result = prime * result + ((getZt() == null) ? 0 : getZt().hashCode());
        result = prime * result + ((getShrq() == null) ? 0 : getShrq().hashCode());
        result = prime * result + ((getAction() == null) ? 0 : getAction().hashCode());
        result = prime * result + ((getIsread() == null) ? 0 : getIsread().hashCode());
        result = prime * result + ((getIsok() == null) ? 0 : getIsok().hashCode());
        result = prime * result + ((getIsshow() == null) ? 0 : getIsshow().hashCode());
        result = prime * result + ((getPkid() == null) ? 0 : getPkid().hashCode());
        result = prime * result + ((getFilenr() == null) ? 0 : getFilenr().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mybook
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", lx=").append(lx);
        sb.append(", subject=").append(subject);
        sb.append(", content=").append(content);
        sb.append(", filename=").append(filename);
        sb.append(", zt=").append(zt);
        sb.append(", shrq=").append(shrq);
        sb.append(", action=").append(action);
        sb.append(", isread=").append(isread);
        sb.append(", isok=").append(isok);
        sb.append(", isshow=").append(isshow);
        sb.append(", pkid=").append(pkid);
        sb.append(", filenr=").append(filenr);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}