package com.lyj.pojo;

import java.io.Serializable;

public class MyBook implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bd_bm.pkid
     *
     * @mbggenerated
     */
    private Short pkid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bd_bm.fgsid
     *
     * @mbggenerated
     */
    private Short fgsid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bd_bm.fid
     *
     * @mbggenerated
     */
    private Short fid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bd_bm.dm
     *
     * @mbggenerated
     */
    private String dm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bd_bm.mc
     *
     * @mbggenerated
     */
    private String mc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bd_bm.zjm
     *
     * @mbggenerated
     */
    private String zjm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bd_bm.lx
     *
     * @mbggenerated
     */
    private String lx;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bd_bm.showid
     *
     * @mbggenerated
     */
    private String showid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bd_bm.showmc
     *
     * @mbggenerated
     */
    private String showmc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bd_bm.dh
     *
     * @mbggenerated
     */
    private String dh;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bd_bm.cz
     *
     * @mbggenerated
     */
    private String cz;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bd_bm.fzr
     *
     * @mbggenerated
     */
    private String fzr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bd_bm.bz
     *
     * @mbggenerated
     */
    private String bz;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bd_bm.isused
     *
     * @mbggenerated
     */
    private String isused;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table bd_bm
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bd_bm.pkid
     *
     * @return the value of bd_bm.pkid
     *
     * @mbggenerated
     */
    public Short getPkid() {
        return pkid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bd_bm.pkid
     *
     * @param pkid the value for bd_bm.pkid
     *
     * @mbggenerated
     */
    public void setPkid(Short pkid) {
        this.pkid = pkid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bd_bm.fgsid
     *
     * @return the value of bd_bm.fgsid
     *
     * @mbggenerated
     */
    public Short getFgsid() {
        return fgsid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bd_bm.fgsid
     *
     * @param fgsid the value for bd_bm.fgsid
     *
     * @mbggenerated
     */
    public void setFgsid(Short fgsid) {
        this.fgsid = fgsid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bd_bm.fid
     *
     * @return the value of bd_bm.fid
     *
     * @mbggenerated
     */
    public Short getFid() {
        return fid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bd_bm.fid
     *
     * @param fid the value for bd_bm.fid
     *
     * @mbggenerated
     */
    public void setFid(Short fid) {
        this.fid = fid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bd_bm.dm
     *
     * @return the value of bd_bm.dm
     *
     * @mbggenerated
     */
    public String getDm() {
        return dm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bd_bm.dm
     *
     * @param dm the value for bd_bm.dm
     *
     * @mbggenerated
     */
    public void setDm(String dm) {
        this.dm = dm == null ? null : dm.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bd_bm.mc
     *
     * @return the value of bd_bm.mc
     *
     * @mbggenerated
     */
    public String getMc() {
        return mc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bd_bm.mc
     *
     * @param mc the value for bd_bm.mc
     *
     * @mbggenerated
     */
    public void setMc(String mc) {
        this.mc = mc == null ? null : mc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bd_bm.zjm
     *
     * @return the value of bd_bm.zjm
     *
     * @mbggenerated
     */
    public String getZjm() {
        return zjm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bd_bm.zjm
     *
     * @param zjm the value for bd_bm.zjm
     *
     * @mbggenerated
     */
    public void setZjm(String zjm) {
        this.zjm = zjm == null ? null : zjm.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bd_bm.lx
     *
     * @return the value of bd_bm.lx
     *
     * @mbggenerated
     */
    public String getLx() {
        return lx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bd_bm.lx
     *
     * @param lx the value for bd_bm.lx
     *
     * @mbggenerated
     */
    public void setLx(String lx) {
        this.lx = lx == null ? null : lx.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bd_bm.showid
     *
     * @return the value of bd_bm.showid
     *
     * @mbggenerated
     */
    public String getShowid() {
        return showid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bd_bm.showid
     *
     * @param showid the value for bd_bm.showid
     *
     * @mbggenerated
     */
    public void setShowid(String showid) {
        this.showid = showid == null ? null : showid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bd_bm.showmc
     *
     * @return the value of bd_bm.showmc
     *
     * @mbggenerated
     */
    public String getShowmc() {
        return showmc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bd_bm.showmc
     *
     * @param showmc the value for bd_bm.showmc
     *
     * @mbggenerated
     */
    public void setShowmc(String showmc) {
        this.showmc = showmc == null ? null : showmc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bd_bm.dh
     *
     * @return the value of bd_bm.dh
     *
     * @mbggenerated
     */
    public String getDh() {
        return dh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bd_bm.dh
     *
     * @param dh the value for bd_bm.dh
     *
     * @mbggenerated
     */
    public void setDh(String dh) {
        this.dh = dh == null ? null : dh.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bd_bm.cz
     *
     * @return the value of bd_bm.cz
     *
     * @mbggenerated
     */
    public String getCz() {
        return cz;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bd_bm.cz
     *
     * @param cz the value for bd_bm.cz
     *
     * @mbggenerated
     */
    public void setCz(String cz) {
        this.cz = cz == null ? null : cz.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bd_bm.fzr
     *
     * @return the value of bd_bm.fzr
     *
     * @mbggenerated
     */
    public String getFzr() {
        return fzr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bd_bm.fzr
     *
     * @param fzr the value for bd_bm.fzr
     *
     * @mbggenerated
     */
    public void setFzr(String fzr) {
        this.fzr = fzr == null ? null : fzr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bd_bm.bz
     *
     * @return the value of bd_bm.bz
     *
     * @mbggenerated
     */
    public String getBz() {
        return bz;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bd_bm.bz
     *
     * @param bz the value for bd_bm.bz
     *
     * @mbggenerated
     */
    public void setBz(String bz) {
        this.bz = bz == null ? null : bz.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bd_bm.isused
     *
     * @return the value of bd_bm.isused
     *
     * @mbggenerated
     */
    public String getIsused() {
        return isused;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bd_bm.isused
     *
     * @param isused the value for bd_bm.isused
     *
     * @mbggenerated
     */
    public void setIsused(String isused) {
        this.isused = isused == null ? null : isused.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bd_bm
     *
     * @mbggenerated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        MyBook other = (MyBook) that;
        return (this.getPkid() == null ? other.getPkid() == null : this.getPkid().equals(other.getPkid()))
            && (this.getFgsid() == null ? other.getFgsid() == null : this.getFgsid().equals(other.getFgsid()))
            && (this.getFid() == null ? other.getFid() == null : this.getFid().equals(other.getFid()))
            && (this.getDm() == null ? other.getDm() == null : this.getDm().equals(other.getDm()))
            && (this.getMc() == null ? other.getMc() == null : this.getMc().equals(other.getMc()))
            && (this.getZjm() == null ? other.getZjm() == null : this.getZjm().equals(other.getZjm()))
            && (this.getLx() == null ? other.getLx() == null : this.getLx().equals(other.getLx()))
            && (this.getShowid() == null ? other.getShowid() == null : this.getShowid().equals(other.getShowid()))
            && (this.getShowmc() == null ? other.getShowmc() == null : this.getShowmc().equals(other.getShowmc()))
            && (this.getDh() == null ? other.getDh() == null : this.getDh().equals(other.getDh()))
            && (this.getCz() == null ? other.getCz() == null : this.getCz().equals(other.getCz()))
            && (this.getFzr() == null ? other.getFzr() == null : this.getFzr().equals(other.getFzr()))
            && (this.getBz() == null ? other.getBz() == null : this.getBz().equals(other.getBz()))
            && (this.getIsused() == null ? other.getIsused() == null : this.getIsused().equals(other.getIsused()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bd_bm
     *
     * @mbggenerated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getPkid() == null) ? 0 : getPkid().hashCode());
        result = prime * result + ((getFgsid() == null) ? 0 : getFgsid().hashCode());
        result = prime * result + ((getFid() == null) ? 0 : getFid().hashCode());
        result = prime * result + ((getDm() == null) ? 0 : getDm().hashCode());
        result = prime * result + ((getMc() == null) ? 0 : getMc().hashCode());
        result = prime * result + ((getZjm() == null) ? 0 : getZjm().hashCode());
        result = prime * result + ((getLx() == null) ? 0 : getLx().hashCode());
        result = prime * result + ((getShowid() == null) ? 0 : getShowid().hashCode());
        result = prime * result + ((getShowmc() == null) ? 0 : getShowmc().hashCode());
        result = prime * result + ((getDh() == null) ? 0 : getDh().hashCode());
        result = prime * result + ((getCz() == null) ? 0 : getCz().hashCode());
        result = prime * result + ((getFzr() == null) ? 0 : getFzr().hashCode());
        result = prime * result + ((getBz() == null) ? 0 : getBz().hashCode());
        result = prime * result + ((getIsused() == null) ? 0 : getIsused().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bd_bm
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", pkid=").append(pkid);
        sb.append(", fgsid=").append(fgsid);
        sb.append(", fid=").append(fid);
        sb.append(", dm=").append(dm);
        sb.append(", mc=").append(mc);
        sb.append(", zjm=").append(zjm);
        sb.append(", lx=").append(lx);
        sb.append(", showid=").append(showid);
        sb.append(", showmc=").append(showmc);
        sb.append(", dh=").append(dh);
        sb.append(", cz=").append(cz);
        sb.append(", fzr=").append(fzr);
        sb.append(", bz=").append(bz);
        sb.append(", isused=").append(isused);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}