package com.lyj.dao;

import com.lyj.pojo.MyBook;

public interface MyBookMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bd_bm
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Short pkid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bd_bm
     *
     * @mbggenerated
     */
    int insert(MyBook record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bd_bm
     *
     * @mbggenerated
     */
    int insertSelective(MyBook record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bd_bm
     *
     * @mbggenerated
     */
    MyBook selectByPrimaryKey(Short pkid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bd_bm
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(MyBook record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bd_bm
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(MyBook record);
}